== Projede Yapılanlar:
* Edittext'lerin visible/invisible özelliklerinin ayarlanması.
* Takım geçişlerinin ayarlanması.
* Doğru/yanlış sayılarının butonlara ve turlara göre arttırılması.
* Final Skoru sayfasının layout ve java dosyalarının düzenlenmesi.
* Bundle ve Intent aracılığıyla verilerin layoutlara aktarılması:
  
[source,java] 
 public void conButton(View view) {
        SeekBar seekBar = (SeekBar) findViewById(R.id.seekBar);
        EditText firstTeam = (EditText)findViewById(R.id.teamFirstEdit);
        EditText secondEdit = (EditText)findViewById(R.id.teamSecondEdit);
        finishScore=seekBar.getProgress();
        spinner = (Spinner) findViewById(R.id.time_select);
        if(spinner.getSelectedItemId()==0)
        {
            countTime=15;
        }
        else if(spinner.getSelectedItemId()==1)
        {
            countTime=30;
        }
        else if(spinner.getSelectedItemId()==2)
        {
            countTime=45;
        }
        else if(spinner.getSelectedItemId()==3)
        {
            countTime=60;
        }
        firstTeamName=firstTeam.getText();
        secondTeamName=secondEdit.getText();
        Intent intent = new Intent(this,MainActivity.class);
        intent.putExtra("skor",finishScore);
        intent.putExtra("first", firstTeam.getText().toString());
        intent.putExtra("second", secondEdit.getText().toString());
        intent.putExtra("time",countTime);
        startActivity(intent);
     
[source,java]   
        getDataBase();
        super.onCreate(savedInstanceState);
        Bundle bundle = getIntent().getExtras();
        finishScore= bundle.getInt("skor");
        team2.name=bundle.getString("second");
        team1.name=bundle.getString("first");
        timeCount = bundle.getInt("time");
        
    
